# Generated by Django 5.2.11 on 2026-02-24 08:10

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SN', models.CharField(max_length=30, unique=True)),
                ('statutProduit', models.CharField(choices=[('OK', 'OK'), ('A_ANALYSER', 'A_ANALYSER'), ('A_REPARER', 'A_REPARER'), ('A_RETESTER', 'A_RETESTER'), ('REBUTER', 'REBUTER')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codeMachine', models.CharField(max_length=10)),
                ('nomMachine', models.CharField(max_length=30)),
                ('typeMachine', models.CharField(choices=[('CMS', 'CMS'), ('VAGUE', 'VAGUE'), ('AOI', 'AOI'), ('ICT', 'ICT'), ('FCT', 'FCT'), ('PROGRAMMATION', 'PROGRAMMATION'), ('VRT', 'VRT'), ('AUTRE', 'AUTRE')], max_length=30)),
                ('anneeMachine', models.IntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2200)])),
                ('versionLogiciel', models.CharField(max_length=30)),
                ('dateDerniereMaintenanceMachine', models.DateField()),
                ('nbPassageMachine', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='OF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroOF', models.CharField(max_length=7, unique=True, validators=[django.core.validators.MinLengthValidator(7), django.core.validators.MaxLengthValidator(7)])),
                ('client', models.CharField(max_length=30)),
                ('dateLancement', models.DateField(blank=True, null=True)),
                ('statutOF', models.CharField(blank=True, choices=[('CREE', 'CREE'), ('EN_COURS', 'EN_COURS'), ('TERMINE', 'TERMINE'), ('INCOMPLET', 'INCOMPLET'), ('BLOQUE', 'BLOQUE')], max_length=30, null=True)),
                ('quantite', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='ReferenceProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PN', models.CharField(max_length=30, unique=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Carte',
            fields=[
                ('produit_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.produit')),
                ('statutCarte', models.CharField(choices=[('OK', 'OK'), ('A_ANALYSER', 'A_ANALYSER'), ('A_REPARER', 'A_REPARER'), ('A_RETESTER', 'A_RETESTER'), ('REBUTER', 'REBUTER')], max_length=30)),
            ],
            bases=('core.produit',),
        ),
        migrations.CreateModel(
            name='Panel',
            fields=[
                ('produit_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.produit')),
                ('nombreCartes', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
            ],
            bases=('core.produit',),
        ),
        migrations.CreateModel(
            name='InterfaceMachine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codeInterface', models.CharField(max_length=10)),
                ('nomInterface', models.CharField(max_length=30)),
                ('anneeInterface', models.IntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2200)])),
                ('nbPassageInterface', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('dateDerniereMaintenanceInterface', models.DateField()),
                ('idMachine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.machine')),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroOperation', models.IntegerField(blank=True, null=True)),
                ('nomOperation', models.CharField(max_length=30)),
                ('typeOperation', models.CharField(choices=[('AUTOMATIQUE', 'AUTOMATIQUE'), ('MANUELLE', 'MANUELLE'), ('TEST', 'TEST'), ('CONTROLE', 'CONTROLE')], max_length=30)),
                ('dateFinOperation', models.DateTimeField(blank=True, null=True)),
                ('idMachine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.machine')),
                ('idOF', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.of')),
            ],
        ),
        migrations.AddField(
            model_name='produit',
            name='idReferenceProduit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.referenceproduit'),
        ),
        migrations.AddField(
            model_name='of',
            name='idReferenceProduit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.referenceproduit'),
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etatTest', models.BooleanField()),
                ('resultatTest', models.CharField(max_length=50)),
                ('codeOperateur', models.IntegerField(blank=True, null=True)),
                ('FPY_flag', models.BooleanField()),
                ('dateFinTest', models.DateTimeField()),
                ('idOperation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.operation')),
                ('idProduit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.produit')),
            ],
        ),
        migrations.CreateModel(
            name='LogTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateEtape', models.DateTimeField(blank=True, null=True)),
                ('numeroEtape', models.IntegerField(blank=True, null=True)),
                ('nomEtape', models.CharField(max_length=50)),
                ('limPlus', models.FloatField(blank=True, null=True)),
                ('limMoins', models.FloatField(blank=True, null=True)),
                ('valeurMesuree', models.FloatField(blank=True, null=True)),
                ('unite', models.CharField(max_length=20)),
                ('resultatEtape', models.CharField(max_length=10)),
                ('composant', models.CharField(blank=True, max_length=10, null=True)),
                ('refComposant', models.CharField(blank=True, max_length=30, null=True)),
                ('face', models.CharField(blank=True, max_length=30, null=True)),
                ('imageTest', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('idTest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.test')),
            ],
        ),
        migrations.CreateModel(
            name='Defaut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroDefaut', models.IntegerField(blank=True, null=True)),
                ('nomDefaut', models.CharField(max_length=50)),
                ('dateDefaut', models.DateTimeField()),
                ('dateRework', models.DateTimeField(blank=True, null=True)),
                ('commentaireDefaut', models.TextField(blank=True, null=True)),
                ('idTest', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.test')),
            ],
        ),
        migrations.CreateModel(
            name='AffectationProduitOF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateAffectation', models.DateTimeField(auto_now_add=True)),
                ('idProduit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectations', to='core.produit')),
                ('idOF', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectations', to='core.of')),
            ],
            options={
                'indexes': [models.Index(fields=['idProduit', 'dateAffectation'], name='core_affect_idProdu_651906_idx'), models.Index(fields=['idOF', 'dateAffectation'], name='core_affect_idOF_id_64fc37_idx')],
                'constraints': [models.UniqueConstraint(fields=('idProduit', 'idOF', 'dateAffectation'), name='uniq_affectation_produit_of_date')],
            },
        ),
        migrations.CreateModel(
            name='CompositionPanel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('idCarte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.carte')),
                ('idPanel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.panel')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('idPanel', 'position'), name='unique_panel_position'), models.UniqueConstraint(fields=('idPanel', 'idCarte'), name='unique_panel_carte')],
            },
        ),
    ]
