# Generated by Django 5.2.11 on 2026-02-24 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='versionLogiciel',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
