# Generated by Django 5.2.11 on 2026-02-24 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_machine_versionlogiciel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='codeMachine',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
