# Generated by Django 5.2.11 on 2026-02-24 09:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_machine_codemachine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interfacemachine',
            name='idMachine',
        ),
        migrations.AddField(
            model_name='machine',
            name='interfaces',
            field=models.ManyToManyField(blank=True, related_name='machines', to='core.interfacemachine'),
        ),
        migrations.AlterField(
            model_name='interfacemachine',
            name='codeInterface',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='interfacemachine',
            name='dateDerniereMaintenanceInterface',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='interfacemachine',
            name='nbPassageInterface',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='machine',
            name='nbPassageMachine',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
