# Generated by Django 5.2.11 on 2026-02-24 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_interfacemachine_idmachine_machine_interfaces_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='interfaces',
            field=models.ManyToManyField(blank=True, null=True, related_name='machines', to='core.interfacemachine'),
        ),
    ]
