# Generated by Django 5.2.11 on 2026-02-24 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_machine_interfaces'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='interfaces',
            field=models.ManyToManyField(blank=True, related_name='machines', to='core.interfacemachine'),
        ),
    ]
