# Generated by Django 5.2.11 on 2026-02-24 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_machine_interfaces'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logtest',
            name='resultatEtape',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='logtest',
            name='unite',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
