# Generated by Django 5.2.11 on 2026-02-25 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_logtest_resultatetape_alter_logtest_unite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machine',
            name='versionLogiciel',
        ),
        migrations.AddField(
            model_name='test',
            name='face',
            field=models.CharField(blank=True, choices=[('TOP', 'TOP'), ('BOTTOM', 'BOTTOM')], max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='versionLogiciel',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
