# Generated by Django 5.2.11 on 2026-02-27 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_machine_versionlogiciel_test_face_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='idRapport',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
