# Generated by Django 5.2.11 on 2026-03-17 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_test_idrapport'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Test',
            new_name='TestProduit',
        ),
    ]
