# Generated by Django 5.2.11 on 2026-03-17 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_rename_test_testproduit'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TestProduit',
            new_name='PassageTest',
        ),
    ]
