# Generated by Django 5.2.11 on 2026-03-25 08:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_rename_testproduit_passagetest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logtest',
            name='imageTest',
        ),
        migrations.AddField(
            model_name='logtest',
            name='messageErreur',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='logtest',
            name='position',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='carte',
            name='statutCarte',
            field=models.CharField(choices=[('OK', 'OK'), ('A analyser', 'A analyser'), ('A réparer', 'A réparer'), ('A retester', 'A retester'), ('Rebut', 'Rebut')], max_length=30),
        ),
        migrations.AlterField(
            model_name='logtest',
            name='face',
            field=models.CharField(blank=True, choices=[('TOP', 'TOP'), ('BOTTOM', 'BOTTOM')], max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='produit',
            name='statutProduit',
            field=models.CharField(choices=[('OK', 'OK'), ('A analyser', 'A analyser'), ('A réparer', 'A réparer'), ('A retester', 'A retester'), ('Rebut', 'Rebut')], max_length=30),
        ),
    ]
