# Generated by Django 5.2.11 on 2026-03-25 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_logtest_imagetest_logtest_messageerreur_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='passagetest',
            name='idInterfaceUtilisee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tests', to='core.interfacemachine'),
        ),
        migrations.AlterField(
            model_name='carte',
            name='statutCarte',
            field=models.CharField(choices=[('OK', 'OK'), ('A_ANALYSER', 'A analyser'), ('A_REPARER', 'A réparer'), ('A_RETESTER', 'A retester'), ('REBUT', 'Rebut')], max_length=30),
        ),
        migrations.AlterField(
            model_name='produit',
            name='statutProduit',
            field=models.CharField(choices=[('OK', 'OK'), ('A_ANALYSER', 'A analyser'), ('A_REPARER', 'A réparer'), ('A_RETESTER', 'A retester'), ('REBUT', 'Rebut')], max_length=30),
        ),
    ]
