# Generated by Django 5.2.11 on 2026-05-22 07:40

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_fix_compositionpanel_schema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compositionpanel',
            name='idPanel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compositions', to='core.panel'),
        ),
        migrations.AlterField(
            model_name='defaut',
            name='nomDefaut',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='logtest',
            name='nomEtape',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='of',
            name='client',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='of',
            name='quantite',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='passagetest',
            name='codeOperateur',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='passagetest',
            name='resultatTest',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='passagetest',
            name='versionLogiciel',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='produit',
            name='SN',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='produit',
            name='idReferenceProduit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.referenceproduit'),
        ),
    ]
